version: 2.0

jobs:
  check:
    docker:
      - image: circleci/openjdk:8-jdk
    environment:
      JVM_OPTS: -Xmx512m
    steps:
      - checkout
      - restore_cache:
          keys:
            - gradle-{{ checksum "build.gradle" }}
      - run:
          name: Run tests
          command: |
            chmod +x ./gradlew
            ./gradlew check
      - run:
          name: Save test results
          command: |
            mkdir -p ~/junit/
            find . -type f -regex ".*/build/test-results/.*xml" -exec cp {} ~/junit/ \;
          when: always
      - store_test_results:
          path: ~/junit
      - store_artifacts:
          path: ~/junit
      - save_cache:
          paths:
            - ~/.gradle
          key: gradle-{{ checksum "build.gradle" }}
  release:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - restore_cache:
          keys:
            - gradle-{{ checksum "build.gradle" }}
      - run:
          name: Release to Maven Central
          command: |
            chmod +x ./gradlew
            ./gradlew clean uploadArchives closeAndReleaseRepository

workflows:
  version: 2

  # runs tests
  check:
    jobs:
      - check            # run unit tests
      - approve-release: # require manual approval in the CircleCI web application.
          type: approval
      - release:         # release to Maven Central
          requires:
            - approve-release
